options:
  formatter: stylish

files:
  include: 'resources/assets/sass/**/*.s+(a|c)ss'
  ignore:
    - 'resources/assets/sass/vendor/**/*.s+(a|c)ss'
    - 'resources/assets/sass/admin/partials/**/*.s+(a|c)ss'

rules:
  attribute-quotes:
    - 1
    -
      include: true

  bem-depth:
    - 1
    -
      max-depth: 1

  border-zero:
    - 1
    -
      convention: '0'

  brace-style:
    - 1
    -
      style: '1tbs'

  class-name-format:
    - 1
    -
      convention: 'hyphenatedbem'

  clean-import-paths:
    - 1
    -
      leading-underscore: false
      filename-extension: false

  empty-args:
    - 1
    -
      include: false

  empty-line-between-blocks:
    - 1
    -
      include: true
      allow-single-line-rulesets: true

  extends-before-declarations: 1

  final-newline:
    - 1
    -
      include: true

  force-attribute-nesting: 1

  force-element-nesting: 1

  force-pseudo-nesting: 1

  function-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'

  hex-length:
    - 1
    -
      style: short

  hex-notation:
    - 1
    -
      style: lowercase

  id-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'

  indentation:
    - 1
    -
      size: 2

  leading-zero:
    - 1
    -
      include: false

  mixin-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'

  mixins-before-declarations: 1

  nesting-depth:
    max-depth: 2

  no-attribute-selectors: 1

  no-color-hex: 1
  no-color-keywords: 1

  no-color-literals:
    - 1
    -
      allow-map-identifiers: true
      allow-rgba: true
      allow-variable-identifiers: true

  no-combinators: 0
  no-css-comments: 1
  no-debug: 0

  no-duplicate-properties:
    - 1
    -
      exclude:
        - background-image

  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1

  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false

  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-universal-selectors: 1
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1

  one-declaration-per-line: 1

  placeholder-in-extend: 1

  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'

  property-sort-order:
    - 1
    -
      order: 'smacss'
      ignore-custom-properties: false

  property-units:
    - 1
    -
      global: ['em', 'px', 'rem', '%', 's']
      per-property: { }

  pseudo-element: 1

  quotes:
    - 1
    -
      style: 'single'

  shorthand-values: 1

  single-line-per-selector: 1

  space-after-bang:
    - 1
    -
      include: false

  space-after-colon:
    - 1
    -
      include: true

  space-after-comma:
    - 1
    -
      include: true

  space-around-operator:
    - 1
    -
      include: true

  space-before-bang:
    - 1
    -
      include: true

  space-before-brace:
    - 1
    -
      include: true

  space-before-colon:
    - 1
    -
      include: false

  space-between-parens:
    - 1
    -
      include: false

  trailing-semicolon:
    - 1
    -
      include: true

  url-quotes: 1

  variable-for-property: 1

  variable-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  zero-unit: 1
